// (?<=No_\d').
const MEDICAL_FORM_ANSWER_TO_DOC_MAP = {
  q1: { true: "Yes", false: "No" },
  q2: { true: "Yes_2", false: "No_2" },
  q3: { true: "Yes_3", false: "No_3" },
  q4: { true: "Yes_4", false: "No_4" },
  q5: { true: "Yes_5", false: "No_5" },
  q6: { true: "Yes_6", false: "No_6" },
  q7: { true: "Si", false: "No_7" },
  q8: { true: "Yes_7", false: "No_8" },
  q9: { true: "Yes_8", false: "No_9" },
  q10: { true: "Yes_9", false: "No_10" },
  q1_1: { true: "Yes_10", false: "No_11" },
  q1_2: { true: "Yes_11", false: "No_12" },
  q1_3: { true: "Yes_12", false: "No_13" },
  q1_4: { true: "Yes_13", false: "No_14" },
  q1_5: { true: "Yes_14", false: "No_15" },
  q2_1: { true: "undefined", false: "undefined_2" },
  q2_2: { true: "Yes_16", false: "No_17" },
  q2_3: { true: "Yes_17", false: "No_18" },
  q2_4: { true: "Yes_18", false: "No_19" },
  qx: { true: "Yes_19", false: "No_20" },
  qx: { true: "Yes_20", false: "No_21" },
  qx: { true: "Yes_21", false: "No_22" },
  qx: { true: "Yes_22", false: "No_23" },
  qx: { true: "undefined_3", false: "undefined_4" },
  qx: { true: "Yes_24", false: "No_25" },
  qx: { true: "Yes_25", false: "No_26" },
  qx: { true: "Yes_26", false: "No_27" },
  qx: { true: "Yes_27", false: "No_28" },
  qx: { true: "Yes_28", false: "No_29" },
  qx: { true: "Yes_29", false: "No_30" },
  qx: { true: "Yes_30", false: "No_31" },
  qx: { true: "Yes_31", false: "No_32" },
  qx: { true: "Yes_32", false: "No_33" },
  qx: { true: "Yes_33", false: "No_34" },
  qx: { true: "Yes_34", false: "No_35" },
  qx: { true: "Yes_35", false: "No_36" },
  qx: { true: "Yes_36", false: "No_37" },
  qx: { true: "Yes_37", false: "No_38" },
  qx: { true: "Yes_38", false: "No_39" },
  qx: { true: "Yes_39", false: "No_40" },
  qx: { true: "Yes_40", false: "No_41" },
  qx: { true: "Yes_41", false: "No_42" },
  qx: { true: "Yes_42", false: "No_43" },
  participantName: [
    "Participant Name Print",
    "Participant",
    "Participant Name",
    "Participant Name2",
  ],
  dob: ["Birthdate", "Birthdate2"],
  date: "Date ddmmyyyy",
};

const MAP_SIGN = {
  MEDICAL: {
    page: 0,
    X: 0.23,
    Y: 0.205,
  },
  CONED: {
    page: 1,
    X: 0.28,
    Y: 0.085,
    GUARDIAN: {
      X: 0.28,
      Y: 0.045,
    },
  },
};

const LIABILITY_FORM_TO_PDF_MAP = {
  id: "1XxaIgvBfxYTAbaH4kCMBXuIqPHQYMqeN",
  title: "Liability Release",
  form: {
    shop: "Store/Resort Name",
    participantName: ["Diver Name", "Diver Name 2"],
    date: "Date DayMonthYear",
    dateMinor: "Date DayMonthYear_2",
    di_yesNo: "No/Yes",
    di_policyNb: "Policy Number",
  },
  signature: {
    page: 1,
    X: 0.275,
    Y: 0.295,
    GUARDIAN: {
      X: 0.275,
      Y: 0.255,
    },
  },
};
